// THIS FILE IS AUTO-GENERATED BY SYNC SCRIPT.
// DO NOT EDIT MANUALLY.
// Snapshot Version: amoy-litetoken-rbac-v1.0.0
// Timestamp: 2026-05-30T10:51:28.000Z
// Chain ID: 80002

export const amoyConfig = {
    contractAddress: '0x506B5ad2aC67bEf1cDAf3748e4576A309ad25657', // Writer Contract
    Erc20Adress: '0xF9BdbE9880ddd8ab387af689006dca08Dd7a0829',       // LITEToken RBAC
    Erc1155Adress: '0xF8C522A8652c0011380331A90cEe1E80325628f2',     // Litera NFT
    UnlockableAddress: '0x9C5457e04441CC28871DB7065559d617566258c5', // Unlockable
    usdtAddress: '', // Not used yet
    chainId: 80002,
    networkName: 'AMOY',
    version: 'amoy-litetoken-rbac-v1.0.0'
};
