// THIS FILE IS AUTO-GENERATED BY SYNC SCRIPT.
// DO NOT EDIT MANUALLY.
// Snapshot Version: pre-amoy-v1.0.0
// Timestamp: 2026-05-28T06:36:16.015Z
// Chain ID: 80002

export const amoyConfigGenerated = {
    contractAddress: '0xb00CAC0568bFa26C951E24Ed43099fADc6443FC4', // Writer Contract
    Erc20Adress: '0x93515CeF6184d2eFC66AD25dad5b995bbC7F357c',       
    Erc1155Adress: '0xF8C522A8652c0011380331A90cEe1E80325628f2',     
    UnlockableAddress: '0x6daa1e88E38db48039D4172258F54Ab0fC4cCA65', 
    usdtAddress: '', // Not used yet
    chainId: 80002,
    networkName: 'AMOY',
    version: 'pre-amoy-v1.0.0'
};
