name: Release WP Plugin

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Prepare Plugin Package
        run: |
          chmod +x package-plugin.sh
          ./package-plugin.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: litera-wp-plugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
